apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      initContainers:
        - name: wait-for-booking-db
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z booking-db 5432; do sleep 2; done;']
        - name: wait-for-kafka
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z kafka 9092; do sleep 2; done;']
      containers:
        - name: booking-service
          image: event-booking/booking-service:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3002
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: PORT_BOOKING_SERVICE
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: LOG_LEVEL
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: KAFKA_BROKERS
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: common-secrets
                  key: DATABASE_URL_BOOKING
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 3002
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health/live
              port: 3002
            initialDelaySeconds: 15
            periodSeconds: 10
