apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: event-booking-prod

resources:
  - ../../base

patches:
  - path: patch-env.yaml
  - path: patch-replicas.yaml
  - path: patch-resources.yaml

images:
  - name: event-booking/user-service
    newTag: v1.0.0
  - name: event-booking/event-service
    newTag: v1.0.0
  - name: event-booking/booking-service
    newTag: v1.0.0
  - name: event-booking/notification-service
    newTag: v1.0.0
