apiVersion: v1
kind: Service
metadata:
  name: {{ include "event-booking.componentFullname" (dict "root" . "component" "notification-service") }}
  namespace: {{ include "event-booking.namespace" . }}
  labels:
    {{- include "event-booking.labels" . | nindent 4 }}
    app.kubernetes.io/component: notification-service
spec:
  type: ClusterIP
  selector:
    {{- include "event-booking.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: notification-service
  ports:
    - name: http
      port: {{ .Values.notificationService.port }}
      targetPort: http

