apiVersion: v1
kind: Service
metadata:
  name: {{ include "event-booking.componentFullname" (dict "root" . "component" "kafka") }}
  namespace: {{ include "event-booking.namespace" . }}
  labels:
    {{- include "event-booking.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
spec:
  type: ClusterIP
  publishNotReadyAddresses: true
  selector:
    {{- include "event-booking.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
  ports:
    - name: broker
      port: {{ .Values.kafka.service.port }}
      targetPort: broker
    - name: controller
      port: {{ .Values.kafka.service.controllerPort }}
      targetPort: controller
