apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: event-booking-dev

resources:
  - ../../base

patches:
  - path: patch-env.yaml

images:
  - name: event-booking/user-service
    newTag: dev
  - name: event-booking/event-service
    newTag: dev
  - name: event-booking/booking-service
    newTag: dev
  - name: event-booking/notification-service
    newTag: dev
