apiVersion: v1
kind: Service
metadata:
  name: {{ include "event-booking.componentFullname" (dict "root" . "component" "user-db") }}
  namespace: {{ include "event-booking.namespace" . }}
  labels:
    {{- include "event-booking.labels" . | nindent 4 }}
    app.kubernetes.io/component: user-db
spec:
  type: ClusterIP
  selector:
    {{- include "event-booking.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: user-db
  ports:
    - name: postgres
      port: {{ .Values.userDb.service.port }}
      targetPort: 5432
