apiVersion: v1
kind: Service
metadata:
  name: event-db
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: event-db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
