apiVersion: v1
kind: Secret
metadata:
  name: common-secrets
type: Opaque
stringData:
  DATABASE_URL_USER: "postgresql://postgres:postgres@user-db:5432/user_db?schema=public"
  DATABASE_URL_EVENT: "postgresql://postgres:postgres@event-db:5432/event_db?schema=public"
  DATABASE_URL_BOOKING: "postgresql://postgres:postgres@booking-db:5432/booking_db?schema=public"
  POSTGRES_PASSWORD: "postgres"
