apiVersion: v1
kind: Service
metadata:
  name: {{ include "event-booking.componentFullname" (dict "root" . "component" "notification-db") }}
  namespace: {{ include "event-booking.namespace" . }}
  labels:
    {{- include "event-booking.labels" . | nindent 4 }}
    app.kubernetes.io/component: notification-db
spec:
  type: ClusterIP
  selector:
    {{- include "event-booking.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: notification-db
  ports:
    - name: postgres
      port: {{ .Values.notificationDb.service.port }}
      targetPort: postgres
