global:
  nodeEnv: development
  logLevel: debug

images:
  userService:
    tag: dev
    pullPolicy: IfNotPresent
  eventService:
    tag: dev
    pullPolicy: IfNotPresent
  bookingService:
    tag: dev
    pullPolicy: IfNotPresent
  notificationService:
    tag: dev
    pullPolicy: IfNotPresent

userService:
  replicaCount: 1

eventService:
  replicaCount: 1

bookingService:
  replicaCount: 1

notificationService:
  replicaCount: 1
