apiVersion: v1
kind: Secret
metadata:
  name: {{ include "event-booking.fullname" . }}-secret
  namespace: {{ include "event-booking.namespace" . }}
  labels:
    {{- include "event-booking.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.databases.postgres.database | quote }}
  POSTGRES_USER: {{ .Values.databases.postgres.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.databases.postgres.password | quote }}
  USER_DATABASE_URL: {{ printf "postgresql://%s:%s@%s:%d/%s" .Values.databases.postgres.username .Values.databases.postgres.password (include "event-booking.componentFqdn" (dict "root" . "component" "user-db")) (int .Values.userDb.service.port) .Values.databases.postgres.database | quote }}
  EVENT_DATABASE_URL: {{ printf "postgresql://%s:%s@%s:%d/%s" .Values.databases.postgres.username .Values.databases.postgres.password (include "event-booking.componentFqdn" (dict "root" . "component" "event-db")) (int .Values.eventDb.service.port) .Values.databases.postgres.database | quote }}
  BOOKING_DATABASE_URL: {{ printf "postgresql://%s:%s@%s:%d/%s" .Values.databases.postgres.username .Values.databases.postgres.password (include "event-booking.componentFqdn" (dict "root" . "component" "booking-db")) (int .Values.bookingDb.service.port) .Values.databases.postgres.database | quote }}
