{{- if .Values.userService.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "event-booking.componentFullname" (dict "root" . "component" "user-service") }}-data
  namespace: {{ include "event-booking.namespace" . }}
  labels:
    {{- include "event-booking.labels" . | nindent 4 }}
    app.kubernetes.io/component: user-service
spec:
  accessModes:
    {{- toYaml .Values.userService.persistence.accessModes | nindent 4 }}
  {{- if .Values.userService.persistence.storageClassName }}
  storageClassName: {{ .Values.userService.persistence.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.userService.persistence.size | quote }}
{{- end }}

