apiVersion: v1
kind: Service
metadata:
  name: booking-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: booking-service
  ports:
    - name: http
      port: 3002
      targetPort: 3002
